"""attempt to zero out

Revision ID: b6e0c8d60e7e
Revises: e91c51ddd805
Create Date: 2023-04-26 10:42:37.255420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6e0c8d60e7e'
down_revision = 'e91c51ddd805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('likes',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('likes',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
