"""added nullable=false to likese column

Revision ID: e91c51ddd805
Revises: 1bc02679131b
Create Date: 2023-04-26 10:19:03.345499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e91c51ddd805'
down_revision = '1bc02679131b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('likes',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('likes',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
